#!/usr/bin/env python3
import argparse
from pathlib import Path
import yaml
import pandas as pd
import numpy as np
from rich import print

HTML_TEMPLATE = '''<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<title>dsmeta QC summary</title>
<style>
 body {{ font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif; margin: 24px; }}
 h1,h2 {{ margin-bottom: 8px; }}
 table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
 th, td {{ border: 1px solid #ddd; padding: 6px 8px; font-size: 13px; }}
 th {{ background: #f3f3f3; text-align: left; }}
 .muted {{ color: #666; }}
 code {{ background: #f6f6f6; padding: 1px 4px; border-radius: 4px; }}
</style>
</head>
<body>
<h1>dsmeta QC summary</h1>
<p class="muted">Project: <b>{project}</b></p>

<h2>Gene-level meta signature</h2>
<p>File: <code>{gene_meta}</code></p>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td># genes in meta table</td><td>{n_genes}</td></tr>
<tr><td># genes FDR &lt; 0.05</td><td>{n_sig}</td></tr>
<tr><td>Median sign concordance</td><td>{med_conc}</td></tr>
<tr><td>Median I2</td><td>{med_i2}</td></tr>
</table>

<h2>Signature lists</h2>
<ul>
<li>Up genes: <code>{up}</code></li>
<li>Down genes: <code>{down}</code></li>
<li>JSON: <code>{jsonp}</code></li>
</ul>

<h2>Pathway meta</h2>
{pathway_section}

<p class="muted">Generated by dsmeta-signature.</p>
</body>
</html>
'''

def fmt(x):
    if x is None or (isinstance(x, float) and (np.isnan(x) or np.isinf(x))):
        return "NA"
    if isinstance(x, float):
        return f"{x:.3f}"
    return str(x)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--workdir", default="work")
    args = ap.parse_args()
    cfg = yaml.safe_load(open(args.config, "r", encoding="utf-8"))
    outdir = Path(cfg["project"]["outdir"])
    repdir = outdir / "reports"
    repdir.mkdir(parents=True, exist_ok=True)

    gene_meta_path = outdir / "signature" / "gene_meta.tsv"
    df = pd.read_csv(gene_meta_path, sep="\t")
    n_genes = len(df)
    n_sig = int((df["fdr"] < 0.05).sum()) if "fdr" in df.columns else 0
    med_conc = float(df["sign_concordance"].median()) if "sign_concordance" in df.columns else None
    med_i2 = float(df["I2"].median()) if "I2" in df.columns else None

    pdir = outdir / "pathways"
    sections = []
    if pdir.exists():
        for f in sorted(pdir.glob("*_meta.tsv")):
            p = pd.read_csv(f, sep="\t")
            sections.append(f"<h3>{f.stem}</h3><p>Top 10 by meta_p</p>")
            top = p.sort_values("meta_p").head(10)
            rows = "".join([
                f"<tr><td>{r['pathway']}</td><td>{int(r['k'])}</td><td>{float(r['concordance']):.2f}</td><td>{float(r['mean_NES']):.2f}</td><td>{float(r['meta_p']):.2e}</td></tr>"
                for _, r in top.iterrows()
            ])
            sections.append("<table><tr><th>Pathway</th><th>k</th><th>Conc</th><th>Mean NES</th><th>Meta p</th></tr>"+rows+"</table>")
    pathway_section = "\n".join(sections) if sections else "<p class='muted'>No pathway meta tables found.</p>"

    html = HTML_TEMPLATE.format(
        project=cfg["project"]["name"],
        gene_meta=str(gene_meta_path),
        n_genes=n_genes,
        n_sig=n_sig,
        med_conc=fmt(med_conc),
        med_i2=fmt(med_i2),
        up=str(outdir/"signature"/"up_genes.txt"),
        down=str(outdir/"signature"/"down_genes.txt"),
        jsonp=str(outdir/"signature"/"disease_signature_meta.json"),
        pathway_section=pathway_section,
    )

    out_html = repdir / "qc_summary.html"
    out_html.write_text(html, encoding="utf-8")
    print(f"[green]Saved report:[/green] {out_html}")

if __name__ == "__main__":
    main()
